apiVersion: tekton.dev/v1alpha1
kind: Run
metadata:
  generateName: cdevent-
spec:
  ref:
    apiVersion: custom.tekton.dev/v0
    kind: CDEvent
  params:
    - name: context
      value:
        type: dev.cdevents.taskrun.notstarted.v1
        source: cdeventerRun
    - name: subject
      value:
        id: myTaskRun123
        taskName: myTask
        url: http://example.com/myTaskRun123
        pipelineRun: myPipelineRun123
