apiVersion: tekton.dev/v1alpha1
kind: Run
metadata:
  generateName: cdevent-
spec:
  ref:
    apiVersion: custom.tekton.dev/v0
    kind: CDEvent
  params:
    - name: context
      value:
        type: dev.cdevents.service.deployed.v1
        source: cdeventerRun
    - name: subject
      value:
        id: myService123
        environmentId: prod123
